import type {Metadata} from 'next';
import {Geist, Geist_Mono} from 'next/font/google';
import './globals.css';
import Link from 'next/link';
import {Toaster} from '@/components/ui/toaster';
import {Input} from '@/components/ui/input';
import {Button} from '@/components/ui/button';
import {Search} from 'lucide-react';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Explora Ciencias',
  description: 'Generated by Firebase Studio',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <div className="bg-background p-4">
          <div className="container mx-auto flex items-center justify-between">
            <Link href="/" className="text-3xl font-semibold text-primary">
              Explora Ciencias
            </Link>
          </div>
        </div>
        <header className="bg-white p-4">
          <nav className="container mx-auto flex items-center justify-between">
            <div className="flex gap-4 items-center">
              <div className="relative flex items-center">
                <Input
                  type="search"
                  placeholder="Search..."
                  className="pr-8 rounded-[6px]"
                />
                <Search className="absolute right-2 h-4 w-4 text-muted-foreground pointer-events-none" />
              </div>
              <Link href="/" className="text-primary hover:text-accent">
                Home
              </Link>
              <Link href="/courses" className="text-primary hover:text-accent">
                Courses
              </Link>
              <Link href="/blog" className="text-primary hover:text-accent">
                Blog
              </Link>
              <Link href="/about" className="text-primary hover:text-accent">
                About
              </Link>
              <Link href="/contact" className="text-primary hover:text-accent">
                Contact
              </Link>
              <div className="flex gap-2">
                <Link href="/login" className="text-primary hover:text-accent px-4 py-2 rounded-md border border-primary">
                  Login
                </Link>
                <Link href="/register" className="text-primary hover:text-accent px-4 py-2 rounded-md border border-primary">
                  Register
                </Link>
              </div>
            </div>
          </nav>
        </header>
        {children}
        <Toaster/>
      </body>
    </html>
  );
}

